# Arquivo: ./prometheus/alerts/alerts.yml

groups:
  - name: infrastructure
    interval: 30s
    rules:
      # ==========================================
      # ALERTAS DE SISTEMA
      # ==========================================
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "CPU alto no host {{ $labels.instance }}"
          description: "CPU está em {{ $value }}% por mais de 5 minutos."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "Memória alta no host {{ $labels.instance }}"
          description: "Uso de memória em {{ $value }}%."

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100 < 15
        for: 5m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "Espaço em disco baixo em {{ $labels.instance }}"
          description: "Apenas {{ $value }}% livre no disco {{ $labels.mountpoint }}."

      # ==========================================
      # ALERTAS DE CONTAINERS
      # ==========================================
      - alert: ContainerDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
          category: container
        annotations:
          summary: "Container {{ $labels.job }} está DOWN"
          description: "O serviço {{ $labels.job }} não está respondendo."

      - alert: ContainerHighMemory
        expr: |
          (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""}) * 100 > 90
          and container_spec_memory_limit_bytes{name!=""} > 0
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "Container {{ $labels.name }} com memória alta"
          description: "Uso de memória em {{ printf \"%.2f\" $value }}%."

      - alert: ContainerHighCPU
        expr: |
          rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "Container {{ $labels.name }} com CPU alto"
          description: "Uso de CPU em {{ printf \"%.2f\" $value }}%."

      # ==========================================
      # ALERTAS DE POSTGRESQL
      # ==========================================
      - alert: PostgresDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          category: database
        annotations:
          summary: "PostgreSQL está DOWN"
          description: "O banco de dados PostgreSQL não está respondendo."

      - alert: PostgresHighConnections
        expr: (pg_stat_database_numbackends / pg_settings_max_connections) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "PostgreSQL com muitas conexões"
          description: "{{ $value }}% das conexões estão em uso."

      - alert: PostgresSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration[5m]) > 300
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "Queries lentas detectadas no PostgreSQL"
          description: "Queries demorando mais de 5 minutos."

      - alert: PostgresHighTransactions
        expr: rate(pg_stat_database_xact_commit[5m]) + rate(pg_stat_database_xact_rollback[5m]) > 10000
        for: 5m
        labels:
          severity: info
          category: database
        annotations:
          summary: "Alto volume de transações no PostgreSQL"
          description: "{{ $value }} transações por segundo."